// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Folder struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Ancestors   []*Folder `json:"ancestors"`
	Descendants []*Folder `json:"descendants"`
	User        *User     `json:"user"`
	Notes       []*Note   `json:"notes"`
}

type Note struct {
	ID      string  `json:"id"`
	Name    string  `json:"name"`
	Content *string `json:"content,omitempty"`
	Folder  *Folder `json:"folder"`
	User    *User   `json:"user"`
}

type User struct {
	ID           string    `json:"id"`
	Name         string    `json:"name"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Salt         string    `json:"salt"`
	CreatedAt    *string   `json:"created_at,omitempty"`
	Folders      []*Folder `json:"folders"`
	Notes        []*Note   `json:"notes"`
}
